In [1]:
import pandas as pd
import numpy as np
from pathlib import Path
from sklearn.model_selection import train_test_split
import tensorflow as tf

In [2]:
def convert_to_icd9(dxStr):
    if dxStr.startswith('E'):
        if len(dxStr) > 4: return dxStr[:4] + '.' + dxStr[4:]
        else: return dxStr
    else:
        if len(dxStr) > 3: return dxStr[:3] + '.' + dxStr[3:]
        else: return dxStr
    
def convert_to_3digit_icd9(dxStr):
    if dxStr.startswith('E'):
        if len(dxStr) > 4: return dxStr[:4]
        else: return dxStr
    else:
        if len(dxStr) > 3: return dxStr[:3]
        else: return dxStr

In [3]:
admission_file = Path('../data/ADMISSIONS.csv')
diagnosis_file = Path('../data/DIAGNOSES_ICD.csv')

In [4]:
admissions_df = pd.read_csv(admission_file)
admissions_df['admittime']= pd.to_datetime(admissions_df['admittime'])
admissions_df['dischtime']= pd.to_datetime(admissions_df['dischtime'])
admissions_df['deathtime']= pd.to_datetime(admissions_df['deathtime'])
admissions_df['edregtime']= pd.to_datetime(admissions_df['edregtime'])
admissions_df['edouttime']= pd.to_datetime(admissions_df['edouttime'])
admissions_df.head()

row_id  subject_id  hadm_id           admittime           dischtime  \
0   12258       10006   142345 2164-10-23 21:09:00 2164-11-01 17:15:00   
1   12263       10011   105331 2126-08-14 22:32:00 2126-08-28 18:59:00   
2   12265       10013   165520 2125-10-04 23:36:00 2125-10-07 15:13:00   
3   12269       10017   199207 2149-05-26 17:19:00 2149-06-03 18:42:00   
4   12270       10019   177759 2163-05-14 20:43:00 2163-05-15 12:00:00   

            deathtime admission_type         admission_location  \
0                 NaT      EMERGENCY       EMERGENCY ROOM ADMIT   
1 2126-08-28 18:59:00      EMERGENCY  TRANSFER FROM HOSP/EXTRAM   
2 2125-10-07 15:13:00      EMERGENCY  TRANSFER FROM HOSP/EXTRAM   
3                 NaT      EMERGENCY       EMERGENCY ROOM ADMIT   
4 2163-05-15 12:00:00      EMERGENCY  TRANSFER FROM HOSP/EXTRAM   

  discharge_location insurance language  religion marital_status  \
0   HOME HEALTH CARE  Medicare      NaN  CATHOLIC      SEPARATED   
1       DEAD/EXPIRED   Private      NaN  CATHOLIC         SINGLE   
2       DEAD/EXPIRED  Medicare      NaN  CATHOLIC            NaN   
3                SNF  Medicare      NaN  CATHOLIC       DIVORCED   
4       DEAD/EXPIRED  Medicare      NaN  CATHOLIC       DIVORCED   

                ethnicity           edregtime           edouttime  \
0  BLACK/AFRICAN AMERICAN 2164-10-23 16:43:00 2164-10-23 23:00:00   
1   UNKNOWN/NOT SPECIFIED                 NaT                 NaT   
2   UNKNOWN/NOT SPECIFIED                 NaT                 NaT   
3                   WHITE 2149-05-26 12:08:00 2149-05-26 19:45:00   
4                   WHITE                 NaT                 NaT   

             diagnosis  hospital_expire_flag  has_chartevents_data  
0               SEPSIS                     0                     1  
1          HEPATITIS B                     1                     1  
2               SEPSIS                     1                     1  
3     HUMERAL FRACTURE                     0                     1  
4  ALCOHOLIC HEPATITIS                     1                     1

In [5]:
diagnosis_df = pd.read_csv(diagnosis_file)
diagnosis_df['icd9_code_converted'] = diagnosis_df['icd9_code'].apply(convert_to_icd9)
diagnosis_df['icd9_code_converted_3digits'] = diagnosis_df['icd9_code'].apply(convert_to_3digit_icd9)
diagnosis_df.head()

row_id  subject_id  hadm_id  seq_num icd9_code icd9_code_converted  \
0  112344       10006   142345        1     99591              995.91   
1  112345       10006   142345        2     99662              996.62   
2  112346       10006   142345        3      5672               567.2   
3  112347       10006   142345        4     40391              403.91   
4  112348       10006   142345        5     42731              427.31   

  icd9_code_converted_3digits  
0                         995  
1                         996  
2                         567  
3                         403  
4                         427

In [6]:
codes_per_admission = diagnosis_df.groupby('hadm_id').agg({
    'icd9_code': lambda x: list(x),
    'icd9_code_converted': lambda x: list(x),
    'icd9_code_converted_3digits': lambda x: list(x),
})
combined_df = pd.merge(admissions_df, codes_per_admission, on=['hadm_id'])
admissions_per_subject = combined_df.groupby('subject_id').agg({
    'hadm_id': lambda x: list(x),
    'admittime': lambda x: list(x),
    'diagnosis': lambda x: list(x),
    'icd9_code': lambda x: list(x),
    'icd9_code_converted': lambda x: list(x),
    'icd9_code_converted_3digits': lambda x: list(x),
})
admissions_per_subject['num_admissions'] = admissions_per_subject['hadm_id'].apply(len)
admissions_per_subject.head()

hadm_id              admittime              diagnosis  \
subject_id                                                           
10006       [142345]  [2164-10-23 21:09:00]               [SEPSIS]   
10011       [105331]  [2126-08-14 22:32:00]          [HEPATITIS B]   
10013       [165520]  [2125-10-04 23:36:00]               [SEPSIS]   
10017       [199207]  [2149-05-26 17:19:00]     [HUMERAL FRACTURE]   
10019       [177759]  [2163-05-14 20:43:00]  [ALCOHOLIC HEPATITIS]   

                                                    icd9_code  \
subject_id                                                      
10006       [[99591, 99662, 5672, 40391, 42731, 4280, 4241...   
10011                [[570, 07030, 07054, 30401, 2875, 2760]]   
10013       [[0389, 41071, 78551, 486, 42731, 20280, 4240,...   
10017       [[81201, 4928, 8028, 8024, 99812, 41511, 2851,...   
10019       [[0389, 51881, 5770, 30390, 5781, 5845, 2848, ...   

                                          icd9_code_converted  \
subject_id                                                      
10006       [[995.91, 996.62, 567.2, 403.91, 427.31, 428.0...   
10011           [[570, 070.30, 070.54, 304.01, 287.5, 276.0]]   
10013       [[038.9, 410.71, 785.51, 486, 427.31, 202.80, ...   
10017       [[812.01, 492.8, 802.8, 802.4, 998.12, 415.11,...   
10019       [[038.9, 518.81, 577.0, 303.90, 578.1, 584.5, ...   

                                  icd9_code_converted_3digits  num_admissions  
subject_id                                                                     
10006       [[995, 996, 567, 403, 427, 428, 424, 424, 287,...               1  
10011                        [[570, 070, 070, 304, 287, 276]]               1  
10013         [[038, 410, 785, 486, 427, 202, 424, 458, 272]]               1  
10017       [[812, 492, 802, 802, 998, 415, 285, 486, E885...               1  
10019       [[038, 518, 577, 303, 578, 584, 284, 572, 785,...               1

In [7]:
relevant_data = admissions_per_subject[admissions_per_subject['num_admissions'] >= 2]
relevant_data

hadm_id  \
subject_id                                                      
10059                                        [142582, 122098]   
10088                                [169938, 168233, 149044]   
10094                                        [168074, 122928]   
10117                                        [187023, 105150]   
10119                                        [157466, 165436]   
10124                                        [182664, 170883]   
40124                                        [126179, 146893]   
40310                                        [186361, 157609]   
41795                                        [138132, 118192]   
41976       [125449, 173269, 176016, 172082, 152032, 13068...   
42135                                        [102203, 117105]   
42346                                        [180391, 175880]   
43881                                        [172454, 167021]   
44083                                [125157, 131048, 198330]   

                                                    admittime  \
subject_id                                                      
10059              [2150-08-07 21:40:00, 2150-08-22 17:33:00]   
10088       [2107-01-04 11:59:00, 2107-01-29 04:00:00, 210...   
10094              [2180-02-29 18:54:00, 2180-03-15 22:35:00]   
10117              [2138-06-05 17:23:00, 2138-11-09 18:08:00]   
10119              [2117-08-05 18:27:00, 2117-08-21 06:58:00]   
10124              [2192-03-26 15:30:00, 2192-04-16 20:57:00]   
40124              [2130-02-04 02:26:00, 2130-08-12 05:49:00]   
40310              [2144-07-11 15:02:00, 2144-12-24 16:16:00]   
41795              [2145-07-07 01:19:00, 2145-09-06 08:52:00]   
41976       [2198-10-29 06:54:00, 2199-01-13 17:13:00, 219...   
42135              [2127-07-23 15:21:00, 2127-10-06 21:00:00]   
42346              [2160-12-16 13:47:00, 2160-12-26 11:45:00]   
43881              [2104-09-24 17:31:00, 2104-10-24 09:44:00]   
44083       [2112-05-04 08:00:00, 2112-05-22 15:37:00, 211...   

                                                    diagnosis  \
subject_id                                                      
10059                        [VARICEAL BLEED, LOWER GI BLEED]   
10088       [SEPSIS;PNEUMONIA;TELEMETRY, CONGESTIVE HEART ...   
10094               [HYPOTENSION;TELEMETRY, SEPSIS;TELEMETRY]   
10117                                          [FEVER, FEVER]   
10119           [ACUTE CHOLECYSTITIS, GASTROINTESTINAL BLEED]   
10124           [LEFT HIP FRACTURE, CONGESTIVE HEART FAILURE]   
40124                        [SHORTNESS OF BREATH, PNEUMONIA]   
40310          [FACIAL NUMBNESS, AROMEGLEY;BURKITTS LYMPHOMA]   
41795       [ASTHMA;CHRONIC OBST PULM DISEASE, ASTHMA;CHRO...   
41976       [PNEUMONIA, HYPOTENSION;UNRESPONSIVE, SEPSIS, ...   
42135                      [FAILURE TO THRIVE, HEPATIC ENCEP]   
42346                                   [PNEUMONIA, VOLVULUS]   
43881              [ACUTE PULMONARY EMBOLISM, UPPER GI BLEED]   
44083       [ESOPHAGEAL CA/SDA, SHORTNESS OF BREATH, PERIC...   

                                                    icd9_code  \
subject_id                                                      
10059       [[5715, 5849, 07070, 2800, 2875, 7895, 45620, ...   
10088       [[0389, 99592, 5990, 78552, 51881, 4280, 2765,...   
10094       [[2273, 486, 5849, 2532, 3970, 4280, 2760, 707...   
10117       [[5290, 7907, 2762, 20300, 2875], [486, 99662,...   
10119       [[5750, 5754, 42731, 7907, 5770, 5849, 5185, 3...   
10124       [[82021, 42832, 4280, 5990, 2851, 42731, 5859,...   
40124       [[486, 5849, 1628, 27651, 2859, 496, 4019], [4...   
40310       [[20020, 51881, 27788, 5845, 48242, 70724, 284...   
41795       [[51881, 49121, 42833, 486, 2761, 29562, 2841,...   
41976       [[0389, 5070, 51881, 5849, 99592, 4019, 25000,...   
42135       [[5722, 5849, 78959, 261, 5724, 2763, 2762, 57...   
42346       [[42821, 486, 51881, 4254, 2764, 5990, 4280, 3...   
43881       [[41519, 

In [8]:
all_symptoms = list(set([item for sublist in relevant_data['icd9_code_converted_3digits'].agg(lambda x: [item for sublist in x for item in sublist]).tolist() for item in sublist]))
vocab = {}
index = 0
for symptom in all_symptoms:
    vocab[symptom] = index
    index = index+1

len(vocab)

150

In [9]:
max_sequence_length = relevant_data['icd9_code_converted_3digits'].apply(len).max()
max_symptoms_per_sequence = relevant_data['icd9_code_converted_3digits'].apply(lambda x: sum([len(y) for y in x])).max()
train_sequences, test_sequences = train_test_split(
    relevant_data['icd9_code_converted_3digits'], 
    test_size=0.1, 
    random_state=12345)
train_sequences.tolist()[5]

[['151', '518', '401', '272'],
 ['511', '423', '401', '285', 'V10'],
 ['423', '511', '423', '285', 'V10', '401']]

In [10]:
def split_sequence(sequence):
    splitted = []
    for split_index in range(1, len(sequence)):
        splitted.append({
            'x': sequence[0:split_index],
            'y': sequence[split_index], 
        })

    return splitted

def split_sequences(sequences):
    splitted_sequences = []
    for sequence in sequences:
        splitted_sequences.extend(split_sequence(sequence))

    return splitted_sequences

def transform_symptoms(symptoms, vocab):
    symptom_vec = np.zeros(len(vocab))
    for symptom in symptoms:
        symptom_vec[vocab[symptom]] = 1
    return tf.convert_to_tensor(symptom_vec)

def translate_and_pad_x_flat(splitted, vocab, max_sequence_length):
    splitted['x_vecs'] = []
    for i in range(max_sequence_length - len(splitted['x'])):
        splitted['x_vecs'].append(transform_symptoms([], vocab))
    for x in splitted['x']:
        splitted['x_vecs'].append(transform_symptoms(x, vocab))
    splitted['x_vecs_stacked'] = tf.stack(splitted['x_vecs'])

def translate_and_pad_x_wide(splitted, vocab, max_symptoms_per_sequence):
    splitted['x_vecs'] = []
    all_symptoms = [symptom for x in splitted['x'] for symptom in x]
    for i in range(max_symptoms_per_sequence - len(all_symptoms)):
        splitted['x_vecs'].append(transform_symptoms([], vocab))
    for symptom in all_symptoms:
        splitted['x_vecs'].append(transform_symptoms([symptom], vocab))
    splitted['x_vecs_stacked'] = tf.stack(splitted['x_vecs'])

def translate_and_pad(splitted, vocab, max_sequence_length, max_symptoms_per_sequence, flat):
    splitted['y_vec'] = transform_symptoms(splitted['y'], vocab)
    if flat:
        translate_and_pad_x_flat(splitted, vocab, max_sequence_length)
    else:
        translate_and_pad_x_wide(splitted, vocab, max_symptoms_per_sequence)
    

def transform_sequences(sequences, vocab, max_sequence_length, max_symptoms_per_sequence, flat=True):
    splitted_sequences = split_sequences(sequences)
    for splitted in splitted_sequences:
        translate_and_pad(splitted, vocab, max_sequence_length, max_symptoms_per_sequence, flat)

    return splitted_sequences


transformed_5 = transform_sequences(train_sequences.tolist()[5:6], vocab, max_sequence_length, max_symptoms_per_sequence, flat=False)
tf.stack([[transformed['y_vec']] for transformed in transformed_5])
tf.stack([transformed['x_vecs_stacked'] for transformed in transformed_5])

<tf.Tensor: shape=(2, 266, 150), dtype=float64, numpy=
array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]])>

In [11]:
train_transformed_flat = transform_sequences(train_sequences.tolist(), vocab, max_sequence_length, max_symptoms_per_sequence, flat=True)
test_transformed_flat = transform_sequences(test_sequences.tolist(), vocab, max_sequence_length, max_symptoms_per_sequence, flat=True)

train_x_flat = tf.stack([transformed['x_vecs_stacked'] for transformed in train_transformed_flat])
train_y_flat = tf.stack([[transformed['y_vec']] for transformed in train_transformed_flat])
test_x_flat = tf.stack([transformed['x_vecs_stacked'] for transformed in test_transformed_flat])
test_y_flat = tf.stack([[transformed['y_vec']] for transformed in test_transformed_flat])

print(train_x_flat.shape)
print(train_y_flat.shape)

(27, 15, 150)
(27, 1, 150)


In [12]:
train_transformed_wide = transform_sequences(train_sequences.tolist(), vocab, max_sequence_length, max_symptoms_per_sequence, flat=False)
test_transformed_wide = transform_sequences(test_sequences.tolist(), vocab, max_sequence_length, max_symptoms_per_sequence, flat=False)

train_x_wide = tf.stack([transformed['x_vecs_stacked'] for transformed in train_transformed_wide])
train_y_wide = tf.stack([[transformed['y_vec']] for transformed in train_transformed_wide])
test_x_wide = tf.stack([transformed['x_vecs_stacked'] for transformed in test_transformed_wide])
test_y_wide = tf.stack([[transformed['y_vec']] for transformed in test_transformed_wide])

print(train_x_wide.shape)
print(train_y_wide.shape)

(27, 266, 150)
(27, 1, 150)


In [13]:
input_layer_flat = tf.keras.layers.Input(shape=(max_sequence_length,len(vocab)))
emb_layer_flat = tf.keras.layers.Dense(64)
lstm_model_flat = tf.keras.models.Sequential([
    input_layer_flat,
    emb_layer_flat,
    tf.keras.layers.LSTM(32, return_sequences=False),
    #tf.keras.layers.Flatten(),
    #tf.keras.layers.Conv1D(filters=32,
    #                       kernel_size=(3,),
    #                       activation='relu'),
    tf.keras.layers.Dense(len(vocab), activation='relu'),
])
lstm_model_flat.compile(loss=tf.keras.losses.BinaryCrossentropy(), optimizer=tf.optimizers.Adam())
lstm_model_flat.fit(x=train_x_flat, y=train_y_flat, epochs=100)

emb_model_flat = tf.keras.models.Sequential([
    input_layer_flat,
    emb_layer_flat,
])
print(emb_model_flat.predict(train_x_flat).shape)

lstm_model_flat.evaluate(test_x_flat, test_y_flat)

Epoch 1/100


ValueError: in user code:

    F:\Users\Lena\Anaconda3\envs\healthcare-aiops\lib\site-packages\tensorflow\python\keras\engine\training.py:806 train_function  *
        return step_function(self, iterator)
    F:\Users\Lena\Anaconda3\envs\healthcare-aiops\lib\site-packages\tensorflow\python\keras\engine\training.py:796 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    F:\Users\Lena\Anaconda3\envs\healthcare-aiops\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:1211 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    F:\Users\Lena\Anaconda3\envs\healthcare-aiops\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:2585 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    F:\Users\Lena\Anaconda3\envs\healthcare-aiops\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:2945 _call_for_each_replica
        return fn(*args, **kwargs)
    F:\Users\Lena\Anaconda3\envs\healthcare-aiops\lib\site-packages\tensorflow\python\keras\engine\training.py:789 run_step  **
        outputs = model.train_step(data)
    F:\Users\Lena\Anaconda3\envs\healthcare-aiops\lib\site-packages\tensorflow\python\keras\engine\training.py:759 train_step
        self.compiled_metrics.update_state(y, y_pred, sample_weight)
    F:\Users\Lena\Anaconda3\envs\healthcare-aiops\lib\site-packages\tensorflow\python\keras\engine\compile_utils.py:388 update_state
        self.build(y_pred, y_true)
    F:\Users\Lena\Anaconda3\envs\healthcare-aiops\lib\site-packages\tensorflow\python\keras\engine\compile_utils.py:318 build
        self._metrics = nest.map_structure_up_to(y_pred, self._get_metric_objects,
    F:\Users\Lena\Anaconda3\envs\healthcare-aiops\lib\site-packages\tensorflow\python\util\nest.py:1135 map_structure_up_to
        return map_structure_with_tuple_paths_up_to(
    F:\Users\Lena\Anaconda3\envs\healthcare-aiops\lib\site-packages\tensorflow\python\util\nest.py:1234 map_structure_with_tuple_paths_up_to
        results = [func(*args, **kwargs) for args in zip(flat_path_list,
    F:\Users\Lena\Anaconda3\envs\healthcare-aiops\lib\site-packages\tensorflow\python\util\nest.py:1234 <listcomp>
        results = [func(*args, **kwargs) for args in zip(flat_path_list,
    F:\Users\Lena\Anaconda3\envs\healthcare-aiops\lib\site-packages\tensorflow\python\util\nest.py:1137 <lambda>
        lambda _, *values: func(*values),  # Discards the path arg.
    F:\Users\Lena\Anaconda3\envs\healthcare-aiops\lib\site-packages\tensorflow\python\keras\engine\compile_utils.py:419 _get_metric_objects
        return [self._get_metric_object(m, y_t, y_p) for m in metrics]
    F:\Users\Lena\Anaconda3\envs\healthcare-aiops\lib\site-packages\tensorflow\python\keras\engine\compile_utils.py:419 <listcomp>
        return [self._get_metric_object(m, y_t, y_p) for m in metrics]
    F:\Users\Lena\Anaconda3\envs\healthcare-aiops\lib\site-packages\tensorflow\python\keras\engine\compile_utils.py:438 _get_metric_object
        metric_obj = metrics_mod.get(metric)
    F:\Users\Lena\Anaconda3\envs\healthcare-aiops\lib\site-packages\tensorflow\python\keras\metrics.py:3483 get
        return deserialize(str(identifier))
    F:\Users\Lena\Anaconda3\envs\healthcare-aiops\lib\site-packages\tensorflow\python\keras\metrics.py:3439 deserialize
        return deserialize_keras_object(
    F:\Users\Lena\Anaconda3\envs\healthcare-aiops\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py:377 deserialize_keras_object
        raise ValueError(

    ValueError: Unknown metric function: 


In [67]:
input_layer_wide = tf.keras.layers.Input(shape=(max_symptoms_per_sequence,len(vocab)))
emb_layer_wide = tf.keras.layers.Dense(64)
lstm_model_wide = tf.keras.models.Sequential([
    input_layer_wide,
    emb_layer_wide,
    tf.keras.layers.LSTM(32, return_sequences=False),
    tf.keras.layers.Dense(len(vocab), activation='relu'),
])
lstm_model_wide.compile(loss=tf.keras.losses.BinaryCrossentropy(), optimizer=tf.optimizers.Adam())
lstm_model_wide.fit(x=train_x_wide, y=train_y_wide, epochs=100)

emb_model_wide = tf.keras.models.Sequential([
    input_layer_wide,
    emb_layer_wide,
])
print(emb_model_wide.predict(train_x_wide).shape)

lstm_model_wide.predict(test_x_wide)

Epoch 1/100
1/1 [==============================] - 0s 1ms/step - loss: 0.9755
Epoch 2/100
1/1 [==============================] - 0s 997us/step - loss: 0.9040
Epoch 3/100
1/1 [==============================] - 0s 996us/step - loss: 0.8483
Epoch 4/100
1/1 [==============================] - 0s 997us/step - loss: 0.7992
Epoch 5/100
1/1 [==============================] - 0s 996us/step - loss: 0.7598
Epoch 6/100
1/1 [==============================] - 0s 996us/step - loss: 0.7328
Epoch 7/100
1/1 [==============================] - 0s 998us/step - loss: 0.6993
Epoch 8/100
1/1 [==============================] - 0s 0s/step - loss: 0.6776
Epoch 9/100
1/1 [==============================] - 0s 999us/step - loss: 0.6575
Epoch 10/100
1/1 [==============================] - 0s 0s/step - loss: 0.6327
Epoch 11/100
1/1 [==============================] - 0s 998us/step - loss: 0.6124
Epoch 12/100
1/1 [==============================] - 0s 0s/step - loss: 0.5927
Epoch 13/100
1/1 [==============================

array([[0.28604686, 0.        , 0.        , 0.12800954, 0.09286939,
        0.19971615, 0.        , 0.5621928 , 0.        , 0.        ,
        0.3773938 , 0.1038178 , 0.03673744, 0.        , 0.1953372 ,
        0.08407849, 0.06606091, 0.28222832, 0.0340192 , 0.02844954,
        0.        , 0.        , 0.        , 0.3019484 , 0.03204484,
        0.09258108, 0.5206683 , 0.        , 0.05568915, 0.1749382 ,
        0.02917202, 0.        , 0.        , 0.02519086, 0.        ,
        0.11564049, 0.37443122, 0.        , 0.02430623, 0.        ,
        0.09621745, 0.26224348, 0.        , 0.01850912, 0.08440626,
        0.        , 0.3528881 , 0.05973257, 0.08944308, 0.06266366,
        0.        , 0.        , 0.06817491, 0.        , 0.        ,
        0.        , 0.35910004, 0.        , 0.13651597, 0.07660159,
        0.        , 0.06914171, 0.04322821, 0.03377157, 0.03910299,
        0.06943193, 0.04450569, 0.03929657, 0.07582685, 0.0285352 ,
        0.03037645, 0.11981416, 0.3888532 , 0.  

In [93]:
prediction = lstm_model_wide.predict(test_x_wide)[0]
np.argwhere(prediction > 0.5)

array([[ 7],
       [26]], dtype=int64)

In [94]:
np.argwhere(test_y_wide[1] == 1)

array([[  0,   7],
       [  0,   8],
       [  0,  23],
       [  0,  25],
       [  0,  26],
       [  0,  35],
       [  0,  51],
       [  0,  56],
       [  0,  73],
       [  0,  78],
       [  0,  84],
       [  0,  85],
       [  0,  87],
       [  0,  89],
       [  0,  90],
       [  0,  95],
       [  0, 117],
       [  0, 118],
       [  0, 123],
       [  0, 133],
       [  0, 135],
       [  0, 143]], dtype=int64)

In [84]:
[(x, vocab[x]) for x in vocab.keys() if vocab[x] in [7, 26]]

[('276', 7), ('995', 26)]